# Generated by Django 5.0.2 on 2025-03-24 15:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model_number", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("purchase_date", models.DateField()),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                ("next_calibration_date", models.DateField(blank=True, null=True)),
                (
                    "calibration_interval_months",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("calibration_due", "Calibration Due"),
                            ("calibration_overdue", "Calibration Overdue"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calibration_date", models.DateField()),
                ("calibrated_by", models.CharField(max_length=200)),
                ("certificate_number", models.CharField(max_length=100)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="calibration_certificates/"
                    ),
                ),
                ("calibration_standard", models.CharField(max_length=200)),
                ("measurement_points", models.JSONField()),
                ("results", models.JSONField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calibrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_records",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Calibration Records",
                "ordering": ["-calibration_date"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_date", models.DateField()),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("corrective", "Corrective"),
                            ("inspection", "Inspection"),
                        ],
                        max_length=50,
                    ),
                ),
                ("performed_by", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("parts_replaced", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-maintenance_date"],
            },
        ),
    ]
