# Generated by Django 5.0.2 on 2025-03-25 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_auto_20250325_0814"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="calibration_interval_months",
        ),
        migrations.AddField(
            model_name="equipment",
            name="calibration_interval_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="calibration_interval_value",
            field=models.IntegerField(
                help_text="Number of intervals between calibrations",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
