# Generated by Django 5.0.2 on 2025-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_remove_equipment_calibration_interval_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="last_calibration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="next_calibration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
